### ISSUE TITLE
关于KVO 释放问题

### ISSUE THREAD

**Issue by CmST0us** [lsmakethebest/LSSafeProtector#19]
你好，我在iOS 12.4上进行了测试。发现现在KVO在dealloc之前如果不将其remove的话也不会崩溃了。
不清楚是我测试代码的问题还是苹果改了KVO的逻辑。可以帮忙验证一下吗？谢谢

**Comment by lsmakethebest** [comment]
开启防护了吗，这个好像没有变化




在2019年08月24日 16:01，eki 写道：

你好，我在iOS 12.4上进行了测试。发现现在KVO在dealloc之前如果不将其remove的话也不会崩溃了。
不清楚是我测试代码的问题还是苹果改了KVO的逻辑。可以帮忙验证一下吗？谢谢

**Comment by CmST0us** [comment]
没有开防护，我取消注释了代码里面testKVO方法里面的123到127行，这时候运行报错，提示NSNotificationTestObject没有实现observeValueForKeyPath方法，为NSNotificationTestObject添加后。可以运行，并且不会发生崩溃。

> 开启防护了吗，这个好像没有变化 在2019年08月24日 16:01，eki 写道： 你好，我在iOS 12.4上进行了测试。发现现在KVO在dealloc之前如果不将其remove的话也不会崩溃了。 不清楚是我测试代码的问题还是苹果改了KVO的逻辑。可以帮忙验证一下吗？谢谢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by lsmakethebest** [comment]
通知在iOS9之后系统就做了处理，不移除通知也不会崩溃




在2019年08月24日 18:42，eki 写道：

没有开防护，我取消注释了代码里面testKVO方法里面的123到127行，这时候运行报错，提示NSNotificationTestObject没有实现observeValueForKeyPath方法，为NSNotificationTestObject添加后。可以运行，并且不会发生崩溃。

开启防护了吗，这个好像没有变化 在2019年08月24日 16:01，eki 写道： 你好，我在iOS 12.4上进行了测试。发现现在KVO在dealloc之前如果不将其remove的话也不会崩溃了。 不清楚是我测试代码的问题还是苹果改了KVO的逻辑。可以帮忙验证一下吗？谢谢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by CmST0us** [comment]
好的多谢，可以提供一下官方变更说明文档吗？麻烦了
